name: PR Checks

on: [pull_request]

jobs:
  linux:
    name: Lints on Linux
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gnome-keyring dbus-x11
          echo $HOME
          mkdir -p /home/runner/.cache/
          mkdir -p /home/runner/.local/share/keyrings/
          chmod 700 -R /home/runner/.local/

      - run: DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork` && echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
      - run: echo 'the-super-secret' | gnome-keyring-daemon --unlock
      - run: eval $(echo 'the-super-secret' | gnome-keyring-daemon --start -d --components secrets) && echo "GNOME_KEYRING_CONTROL=$GNOME_KEYRING_CONTROL" >> $GITHUB_ENV

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - run: |
          cargo run --example example

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  mac:
    name: Checks for Mac
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: x86_64-apple-darwin

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example example

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  windows:
    name: Lints on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example example

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
